export const userPublicColumns = {
  id: true,
  name: true,
  displayName: true,
  image: true,
  isVerified: true,
  isExpert: true,
  badgeType: true,
} as const;

export const userAuthColumns = {
  id: true,
  email: true,
  name: true,
  displayName: true,
  image: true,
  phone: true,
  bio: true,
  gender: true,
  ageGroup: true,
  nationality: true,
  status: true,
  suspendedUntil: true,
  isVerified: true,
  isProfileComplete: true,
  verifiedRequestId: true,
  verifiedAt: true,
  isExpert: true,
} as const;

export const userMeColumns = {
  id: true,
  name: true,
  email: true,
  displayName: true,
  image: true,
  phone: true,
  bio: true,
  gender: true,
  ageGroup: true,
  nationality: true,
  status: true,
  suspendedUntil: true,
  isVerified: true,
  isExpert: true,
  isProfileComplete: true,
  notifyAnswers: true,
  notifyComments: true,
  notifyReplies: true,
  notifyAdoptions: true,
  notifyFollows: true,
  userType: true,
  visaType: true,
  interests: true,
  preferredLanguage: true,
  onboardingCompleted: true,
  koreanLevel: true,
  createdAt: true,
  updatedAt: true,
} as const;
